---
- name: Pull docker image of Calculator
  hosts: all
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: pull docker image
      shell: sudo docker pull ashu07soni/auto_calculator

#    - name: running container
#      shell: docker run -it -d ashu07soni/auto_calculator